// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockScoreService.API.Data;

#nullable disable

namespace MockScoreService.API.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    partial class FootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MockScoreService.API.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emblem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FL1",
                            Emblem = "https://crests.football-data.org/FL1.png",
                            Name = "Ligue 1",
                            Type = "LEAGUE"
                        });
                });

            modelBuilder.Entity("MockScoreService.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HalfTimeAwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HalfTimeHomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matchday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            CompetitionId = 1,
                            HomeTeamId = 1,
                            LastUpdated = new DateTime(2026, 1, 20, 17, 6, 55, 878, DateTimeKind.Utc).AddTicks(3919),
                            Matchday = 20,
                            SeasonId = 1,
                            Stage = "REGULAR_SEASON",
                            Status = "SCHEDULED",
                            UtcDate = new DateTime(2026, 1, 21, 17, 6, 55, 878, DateTimeKind.Utc).AddTicks(3903)
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            CompetitionId = 1,
                            HomeTeamId = 3,
                            LastUpdated = new DateTime(2026, 1, 20, 17, 6, 55, 878, DateTimeKind.Utc).AddTicks(3923),
                            Matchday = 20,
                            SeasonId = 1,
                            Stage = "REGULAR_SEASON",
                            Status = "SCHEDULED",
                            UtcDate = new DateTime(2026, 1, 21, 20, 6, 55, 878, DateTimeKind.Utc).AddTicks(3921)
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            CompetitionId = 1,
                            HomeTeamId = 5,
                            LastUpdated = new DateTime(2026, 1, 20, 17, 6, 55, 878, DateTimeKind.Utc).AddTicks(3926),
                            Matchday = 20,
                            SeasonId = 1,
                            Stage = "REGULAR_SEASON",
                            Status = "SCHEDULED",
                            UtcDate = new DateTime(2026, 1, 22, 17, 6, 55, 878, DateTimeKind.Utc).AddTicks(3924)
                        });
                });

            modelBuilder.Entity("MockScoreService.API.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMatchday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentMatchday = 20,
                            EndDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MockScoreService.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crest")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crest = "https://crests.football-data.org/524.png",
                            Name = "Paris Saint-Germain FC",
                            ShortName = "Paris SG",
                            Tla = "PSG"
                        },
                        new
                        {
                            Id = 2,
                            Crest = "https://crests.football-data.org/516.png",
                            Name = "Olympique de Marseille",
                            ShortName = "Marseille",
                            Tla = "MAR"
                        },
                        new
                        {
                            Id = 3,
                            Crest = "https://crests.football-data.org/523.png",
                            Name = "Olympique Lyonnais",
                            ShortName = "Lyon",
                            Tla = "LYO"
                        },
                        new
                        {
                            Id = 4,
                            Crest = "https://crests.football-data.org/548.png",
                            Name = "AS Monaco FC",
                            ShortName = "Monaco",
                            Tla = "MON"
                        },
                        new
                        {
                            Id = 5,
                            Crest = "https://crests.football-data.org/521.png",
                            Name = "LOSC Lille",
                            ShortName = "Lille",
                            Tla = "LIL"
                        },
                        new
                        {
                            Id = 6,
                            Crest = "https://crests.football-data.org/522.png",
                            Name = "OGC Nice",
                            ShortName = "Nice",
                            Tla = "NIC"
                        },
                        new
                        {
                            Id = 7,
                            Crest = "https://crests.football-data.org/529.png",
                            Name = "Stade Rennais FC",
                            ShortName = "Rennes",
                            Tla = "REN"
                        },
                        new
                        {
                            Id = 8,
                            Crest = "https://crests.football-data.org/546.png",
                            Name = "RC Lens",
                            ShortName = "Lens",
                            Tla = "LEN"
                        });
                });

            modelBuilder.Entity("MockScoreService.API.Models.Match", b =>
                {
                    b.HasOne("MockScoreService.API.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MockScoreService.API.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockScoreService.API.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MockScoreService.API.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });
#pragma warning restore 612, 618
        }
    }
}
